export const fileData ={
    Home: "New Castle",
    variables: [
        {
            id: 1,
            variable: "x1",
            code: "HTP",
            name: "Home Total Points",
            type: "Home",
            value: 22,
        },
        {
            id: 2,
            variable: "x2",
            code: "HTG",
            name: "Home Total Goals",
            type: "Home",
            value: 22,
        },
        {
            id: 3,
            variable: "x3",
            code: "HTD",
            name: "Home Total Defence",
            type: "Home",
            value: 22,
        },
        {
            id: 4,
            variable: "x4",
            code: "HMP",
            name: "Home Match Played",
            type: "Home",
            value: 22,
        },
        {
            id: 5,
            variable: "x5",
            code: "HLR",
            name: "Home Last Result",
            type: "Home",
            value: 22,
        },
        {
            id: 6,
            variable: "x6",
            code: "HLGS",
            name: "Home Last Goals Scored",
            type: "Home",
            value: 22,
        },
        {
            id: 7,
            variable: "x7",
            code: "HLGS",
            name: "Home Last Goals Conceded",
            type: "Home",
            value: 22,
        },
        {
            id: 8,
            variable: "x8",
            code: "HGSMA",
            name: "Home Goals Scored Moving Average",
            type: "Home",
            value: 22,
        },
        {
            id: 9,
            variable: "x9",
            code: "HGCMA",
            name: "Home Goals Conceded Moving Average",
            type: "Home",
            value: 22,
        },
        {
            id: 10,
            variable: "x10",
            code: "HLOTP",
            name: "Home Last Opponent Total Points",
            type: "Home",
            value: 22,
        },
        {
            id: 11,
            variable: "x11",
            code: "HLOTG",
            name: "Home Last Opponent Total Goals",
            type: "Home",
            value: 22,
        },
        {
            id: 12,
            variable: "x12",
            code: "HLOTD",
            name: "Home Last Opponent Total Defence",
            type: "Home",
            value: 22,
        },
        {
            id: 13,
            variable: "x13",
            code: "HLOMP",
            name: "Home Shadow Score",
            type: "Home",
            value: 22,
        },
        {
            id: 14,
            variable: "x14",
            code: "HR1",
            name: "Home Rate 1",
            type: "Home",
            value: 22,
        },
        {
            id: 15,
            variable: "x15",
            code: "HR2",
            name: "Home Rate 2",
            type: "Home",
            value: 22,
        },
        {
            id: 16,
            variable: "x16",
            code: "HGS",
            name: "Home Global Score",
            type: "Home",
            value: 22,
        },
        {
            id: 17,
            variable: "x17",
            code: "HL",
            name: "Home Logarithm",
            type: "Home",
            value: 22,
        },
        {
            id: 18,
            variable: "x18",
            code: "HL6R",
            name: "Home Last 6 Results",
            type: "Home",
            value: 22,
        },
        {
            id: 19,
            variable: "x19",
            code: "HGSR",
            name: "Home Goals Scored Ratio",
            type: "Home",
            value: 22,
        },
        {
            id: 20,
            variable: "x20",
            code: "HHGSR",
            name: "Home Highest Goal Scored Ratio",
            type: "Home",
            value: 22,
        },
        // Variables de type "Away"
        {
            id: 21,
            variable: "y1",
            code: "ATP",
            name: "Away Total Points",
            type: "Away",
            value: 22,
        },
        {
            id: 22,
            variable: "y2",
            code: "ATG",
            name: "Away Total Goals",
            type: "Away",
            value: 22,
        },
        {
            id: 23,
            variable: "y3",
            code: "ATD",
            name: "Away Total Defence",
            type: "Away",
            value: 22,
        },
        {
            id: 24,
            variable: "y4",
            code: "AMP",
            name: "Away Match Played",
            type: "Away",
            value: 22,
        },
        {
            id: 25,
            variable: "y5",
            code: "ALR",
            name: "Away Last Result",
            type: "Away",
            value: 22,
        },
        {
            id: 26,
            variable: "y6",
            code: "ALGS",
            name: "Away Last Goals Scored",
            type: "Away",
            value: 22,
        },
        {
            id: 27,
            variable: "y7",
            code: "ALGS",
            name: "Away Last Goals Conceded",
            type: "Away",
            value: 22,
        },
        {
            id: 28,
            variable: "y8",
            code: "AGSMA",
            name: "Away Goals Scored Moving Average",
            type: "Away",
            value: 22,
        },
        {
            id: 29,
            variable: "y9",
            code: "AGCMA",
            name: "Away Goals Conceded Moving Average",
            type: "Away",
            value: 22,
        },
        {
            id: 30,
            variable: "y10",
            code: "ALOTP",
            name: "Away Last Opponent Total Points",
            type: "Away",
            value: 22,
        },
        {
            id: 31,
            variable: "y11",
            code: "ALOTG",
            name: "Away Last Opponent Total Goals",
            type: "Away",
            value: 22,
        },
        {
            id: 32,
            variable: "y12",
            code: "ALOTD",
            name: "Away Last Opponent Total Defence",
            type: "Away",
            value: 22,
        },
        {
            id: 33,
            variable: "y13",
            code: "ALOMP",
            name: "Away Shadow Score",
            type: "Away",
            value: 22,
        },
        {
            id: 34,
            variable: "y14",
            code: "AR1",
            name: "Away Rate 1",
            type: "Away",
            value: 22,
        },
        {
            id: 35,
            variable: "y15",
            code: "AR2",
            name: "Away Rate 2",
            type: "Away",
            value: 22,
        },
        {
            id: 36,
            variable: "y16",
            code: "AGS",
            name: "Away Global Score",
            type: "Away",
            value: 22,
        },
        {
            id: 37,
            variable: "y17",
            code: "AL",
            name: "Away Logarithm",
            type: "Away",
            value: 22,
        },
        {
            id: 38,
            variable: "y18",
            code: "AL6R",
            name: "Away Last 6 Results",
            type: "Away",
            value: 22,
        },
        {
            id: 39,
            variable: "y19",
            code: "AGSR",
            name: "Away Goals Scored Ratio",
            type: "Away",
            value: 22,
        },
        {
            id: 40,
            variable: "y20",
            code: "AHGSR",
            name: "Away Highest Goal Scored Ratio",
            type: "Away",
            value: 29,
        }
    ]
};
